id: P004403
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159526
  title: དིང་གླིང་ཁེར་འབུད།
  author: ''
  volumes:
    eab6658813ff445da6079df954468375:
      image_group_id: I2PD18360
      title: ''
      volume_number: 1
      total_pages: 300
      base_file: v001.txt
